<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-01-24T16:58:40 IST" name="Suite" finished-at="2024-01-24T16:59:11 IST" duration-ms="30352">
    <groups>
    </groups>
    <test started-at="2024-01-24T16:58:40 IST" name="Test" finished-at="2024-01-24T16:59:11 IST" duration-ms="30352">
      <class name="firstclass.TestTwo">
        <test-method signature="testTwo()[pri:0, instance:firstclass.TestTwo@61df66b6]" started-at="2024-01-24T16:58:40 IST" name="testTwo" finished-at="2024-01-24T16:58:51 IST" duration-ms="11159" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTwo -->
      </class> <!-- firstclass.TestTwo -->
      <class name="firstclass.TestThree">
        <test-method signature="testThree()[pri:0, instance:firstclass.TestThree@1dde4cb2]" started-at="2024-01-24T16:58:51 IST" name="testThree" finished-at="2024-01-24T16:58:59 IST" duration-ms="7822" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testThree -->
      </class> <!-- firstclass.TestThree -->
      <class name="firstclass.LoginTest">
        <test-method is-config="true" signature="openApplication()[pri:0, instance:firstclass.LoginTest@56620197]" started-at="2024-01-24T16:59:01 IST" name="openApplication" finished-at="2024-01-24T16:59:04 IST" duration-ms="3078" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method signature="login(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:firstclass.LoginTest@56620197]" started-at="2024-01-24T16:59:04 IST" name="login" data-provider="getLoginData" finished-at="2024-01-24T16:59:06 IST" duration-ms="1568" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[khushi@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[khushi]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Success]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:firstclass.LoginTest@56620197]" started-at="2024-01-24T16:59:06 IST" name="tearDown" finished-at="2024-01-24T16:59:06 IST" duration-ms="359" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="openApplication()[pri:0, instance:firstclass.LoginTest@56620197]" started-at="2024-01-24T16:59:06 IST" name="openApplication" finished-at="2024-01-24T16:59:09 IST" duration-ms="2671" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method signature="login(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:firstclass.LoginTest@56620197]" started-at="2024-01-24T16:59:09 IST" name="login" data-provider="getLoginData" finished-at="2024-01-24T16:59:10 IST" duration-ms="1561" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[khu233]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Failure]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Failure] but found [Success]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Failure] but found [Success]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at firstclass.LoginTest.login(LoginTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:firstclass.LoginTest@56620197]" started-at="2024-01-24T16:59:10 IST" name="tearDown" finished-at="2024-01-24T16:59:11 IST" duration-ms="234" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- firstclass.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
